Update annuaire.csv
senegalouvert/annuaire-sites-publics-senegal pull request #4
Opened 2021-03-01 19:50 UTC by 0SansNom

2021-03-01 20:45 UTC, dofbi commented on data/annuaire.csv
> +Comité Interministériel de Lutte contre la Drogue,http://www.cild.gouv.sn/,Portail
Je pense que nous allons supprimer les protocoles http:// ou https:// pour tous donc pas besoin de modiffier

2021-03-01 20:46 UTC, dofbi commented on data/annuaire.csv
> +Radiodiffusion télévision sénégalaise,http://www.rts.sn/,Service
Sur le site [rts.sn](http://www.rts.sn) il n'y a pas de service en ligne juste un site administratif

2021-03-22 02:09 UTC, dofbi requested changes
Hello @0SansNom 
J'attends tes modifications pour merge
Merci encore

2021-03-22 04:52 UTC, 0SansNom reviewed
following your comments, I have do changes

2021-03-22 06:30 UTC, merged